### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by designrans** [sdbds/stable-diffusion-webui-wildcards#6]
*** Error running process: D:\sd-webui-aki-v4.3\extensions\sd-webui-wildcards-ad\scripts\wildcards.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.3\modules\scripts.py", line 619, in process
        script.process(p, *script_args)
      File "D:\sd-webui-aki-v4.3\extensions\sd-webui-wildcards-ad\scripts\wildcards.py", line 39, in process
        if(not hasattr(shared.Shared, "d_replacements") or getattr(p,"_ad_idx",-1) == -1):
    AttributeError: module 'modules.shared' has no attribute 'Shared'

**Comment by sdbds** [comment]
适配的1.6.0
